# Generated by Django 3.2.19 on 2023-06-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='token_m',
        ),
    ]
