# Generated by Django 3.2.19 on 2023-06-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_passwordresetcodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='this_user',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user',
            new_name='this_user',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
