# Generated by Django 3.2.19 on 2023-06-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20230626_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='edit_mod',
            field=models.BooleanField(default=False),
        ),
    ]
