# Generated by Django 3.2.19 on 2023-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_income_edit_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='edit_mod',
            field=models.BooleanField(default=False),
        ),
    ]
